id = "golang-snippets"
name = "Golang Snippets"
version = "0.2.0"
schema_version = 1
authors = ["zulerne"]
description = "Minimal Go snippets with short prefixes for Zed."
repository = "https://github.com/zulerne/zed-go-snippets"
snippets = ["./snippets/go.json"]
